chat_endpoint: databricks-dbrx-instruct
chat_endpoint_parameters:
  max_tokens: 500
  temperature: 0.01
chat_prompt_template: 'You are a trusted assistant that helps answer questions based
  only on the provided information. If you do not know the answer to a question, you
  truthfully say you do not know.  Here is some context which might or might not help
  you answer: {context}.  Answer directly, do not repeat the question, do not start
  with something like: the answer to the question, do not add AI in front of your
  answer, do not say: here is the answer, do not mention the context or the question.
  Based on this context, answer this question: {question}'
chat_prompt_template_variables:
- context
- question
chunk_template: '`{chunk_text}`

  '
query_rewriter_prompt_template: 'Based on the chat history below, we want you to generate
  a query for an external data source to retrieve relevant documents so that we can
  better answer the question. The query should be in natural language. The external
  data source uses similarity search to search for relevant documents in a vector
  space. So the query should be similar to the relevant documents semantically. Answer
  with only the query. Do not add explanation.


  Chat history: {chat_history}


  Question: {question}'
query_rewriter_prompt_template_variables:
- chat_history
- question
vector_search_endpoint_name: rag_endpoint
vector_search_index: niall_dev.rag.gold_rag_demo_pdfs_chunked_index
vector_search_parameters:
  k: 3
vector_search_schema:
  chunk_text: chunked_text
  document_source: doc_uri
  primary_key: chunk_id
